name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - uses: nrwl/nx-set-shas@v3
      - name: lint, test and build
        working-directory: ./frontend
        run: |
          npm install
          git branch --track main origin/main
          npm run ci

      - name: compress build artifact for deployment
        working-directory: ./frontend/dist/apps/lectoraat-smart-energy-web/browser
        run: |
          tar caf "${GITHUB_WORKSPACE}/frontend-artifact.tar.zst" .

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: frontend-artifact.tar.zst